### ISSUE TITLE
GOannotation task page for review

### ISSUE THREAD

**Issue by CharlesD1ng** [hyginn/rete#100]
ToDo requirements are ready for review. You can find it here [http://steipe.biochemistry.utoronto.ca/abc/students/index.php/BCB420_2017_Tasks/GOannotations#Workflow].

A few questions:
Most packages for obo files I found does not parse namespace, which indicates the three ontology, I guess I have to parse just for that attribute manually?
when a node is found with single parent and child and no annotation, how is its name passed to the child, GO ID? gene symbol into child's children vector? 

Thanks

**Comment by hyginn** [comment]
Comments added on task page. Needs revision, then raise another Issue.

 >Most packages for obo files I found does not parse namespace, [...]

Why do you want to use a package?

 > when a node is found with single parent and child and no annotation, how is its name passed to the child, GO ID? gene symbol into child's children vector?

Do you mean when you are deleting this node from the DAG? Initially, you record the name of each term. If you delete an intermediate node from the DAG, you add the name of the deleted node to it's child, either as a vector element, or with a separator character like ":". Thus you record that that node now represents two terms (You could do this in a more principled way, but it would depend on a use case whether that's necessary.). The goal is to simplify the DAG and remove terms that are not informative.
