### ISSUE TITLE
Pseudocode and test cases for importConservation.

### ISSUE THREAD

**Issue by Adriel-M** [hyginn/rete#101]
https://github.com/hyginn/rete/pull/90

**Comment by hyginn** [comment]
Some minor comments added. Next: for the part that adds the annotations to GeneData.

The simplest way to develop your function is with the test ```geneData```  list objects I have produced for you here:
http://steipe.biochemistry.utoronto.ca/abc/students/index.php/User:Sabrina.ge/Tasks/SNV_Genes_data_struct#Development_data_examples
