### ISSUE TITLE
importPDB.R

### ISSUE THREAD

**Issue by bagherig** [hyginn/rete#103]
Hi Boris, I had a small question regarding the input to my function. Is the GeneData resource object going to be given to the function as an input parameter or should my function load the GeneData object from `inst/extdata/`? Thanks.

**Comment by hyginn** [comment]
We need to distinguish between script, and function. There should be a script that iterates over all genes in GeneData. The script takes one $xyzMap object from the geneData entry for a gene, and assigns one $xyz object back into the list. Thus the function's input would be the xyzMap data frame (in memory), and the function's return value is the $xyz list of data frames.

Does this make sense?
Boris

**Comment by bagherig** [comment]
Yes that makes sense.
Thank you
