### ISSUE TITLE
SEL3D comments addressed 

### ISSUE THREAD

**Issue by ghost** [hyginn/rete#105]
Some notes:
Blast is now local, but the user must have local blast installed and added to the path.  Additionally, if they run this on Rstudio, they must open Rstudio from command line with the -a argument so that it imports environment variables (eg $PATH).  This has been mentioned on the task page now.

Results now only include human proteins, and no alignment will be outputted that has any gaps.

==> devtools::check(document = FALSE)

Setting env vars ---------------------------------------------------------------
CFLAGS  : -Wall -pedantic
CXXFLAGS: -Wall -pedantic
Building rete ------------------------------------------------------------------
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ  \
  --no-save --no-restore --quiet CMD build  \
  '/Users/Lindsay/Documents/School/Fourth Year/BCB420/rete' --no-resave-data  \
  --no-manual 

* checking for file ‘/Users/Lindsay/Documents/School/Fourth Year/BCB420/rete/DESCRIPTION’ ... OK
* preparing ‘rete’:
* checking DESCRIPTION meta-information ... OK
* checking for LF line-endings in source and make files
* checking for empty or unneeded directories
* building ‘rete_0.1.0.tar.gz’

Setting env vars ---------------------------------------------------------------
_R_CHECK_CRAN_INCOMING_ : FALSE
_R_CHECK_FORCE_SUGGESTS_: FALSE
Checking rete ------------------------------------------------------------------
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ  \
  --no-save --no-restore --quiet CMD check  \
  '/var/folders/t5/gjyzf11x33bdjr1wst8f0zmw0000gn/T//RtmpvcrWXO/rete_0.1.0.tar.gz'  \
  --as-cran --timings --no-manual 

* using log directory ‘/Users/Lindsay/Documents/School/Fourth Year/BCB420/rete.Rcheck’
* using R version 3.3.2 (2016-10-31)
* using platform: x86_64-apple-darwin13.4.0 (64-bit)
* using session charset: UTF-8
* using options ‘--no-manual --as-cran’
* checking for file ‘rete/DESCRIPTION’ ... OK
* checking extension type ... Package
* this is package ‘rete’ version ‘0.1.0’
* package encoding: UTF-8
* checking package namespace information ... OK
* checking package dependencies ... OK
* checking if this is a source package ... OK
* checking if there is a namespace ... OK
* checking for executable files ... OK
* checking for hidden files and directories ... OK
* checking for portable file names ... OK
* checking for sufficient/correct file permissions ... OK
* checking whether package ‘rete’ can be installed ... OK
* checking installed package size ... NOTE
  installed size is 116.0Mb
  sub-directories of 1Mb or more:
    extdata  115.0Mb
* checking package directory ... OK
* checking DESCRIPTION meta-information ... OK
* checking top-level files ... OK
* checking for left-over files ... OK
* checking index information ... OK
* checking package subdirectories ... OK
* checking R files for non-ASCII characters ... OK
* checking R files for syntax errors ... OK
* checking whether the package can be loaded ... OK
* checking whether the package can be loaded with stated dependencies ... OK
* checking whether the package can be unloaded cleanly ... OK
* checking whether the namespace can be loaded with stated dependencies ... OK
* checking whether the namespace can be unloaded cleanly ... OK
* checking loading without being on the library search path ... OK
* checking dependencies in R code ... OK
* checking S3 generic/method consistency ... OK
* checking replacement functions ... OK
* checking foreign function calls ... OK
* checking R code for possible problems ... OK
* checking Rd files ... OK
* checking Rd metadata ... OK
* checking Rd line widths ... OK
* checking Rd cross-references ... OK
* checking for missing documentation entries ... OK
* checking for code/documentation mismatches ... OK
* checking Rd \usage sections ... OK
* checking Rd contents ... OK
* checking for unstated dependencies in examples ... OK
* checking examples ... OK
* checking for unstated dependencies in ‘tests’ ... OK
* checking tests ...
  Running ‘testthat.R’ OK
* DONE
Status: 1 NOTE
checking installed package size ... NOTE
  installed size is 116.0Mb
  sub-directories of 1Mb or more:
    extdata  115.0Mb

See
  ‘/Users/Lindsay/Documents/School/Fourth Year/BCB420/rete.Rcheck/00check.log’
for details.

R CMD check results
0 errors | 0 warnings | 1 note 

R CMD check succeeded

**Comment by hyginn** [comment]
Reviewed.
