### ISSUE TITLE
Goannotation model

### ISSUE THREAD

**Issue by CharlesD1ng** [hyginn/rete#106]
edit 2: the pseudo-code for the function and unittests for GOannotation are for review, as well as synthesized data.

edit 1: Please have a look at the revised task page 
http://steipe.biochemistry.utoronto.ca/abc/students/index.php/BCB420_2017_Tasks/GOannotations#Workflow
Sorry I went ahead before getting a confirmative answer on using package to read gaf.

Hi, just to make sure my understanding of the model is compatible to want is expected.
I am picturing a tree with structure
[http://webdocs.cs.ualberta.ca/~bioinfo/PA/GO/images/3aspects.gif](url),
with the top node being the name of the rds and each of 3 ontology has their own DAG.

Also, for the packages (msga) readGAF that parses .GAF files, since the gaf files only need to be read once and store the corresponding annotation to be used to check for GO terms in the DAG, there will be no duplicate parsing/reading files. The function basically store every terms  as sets that contain items (annotation), so makes it quite easy to query any annotation associated to the GO term
 (e.g.).
to find gene symbols annotated to GO:2001257
I can do
GOA@itemAnnotations[GOA@sets[names(GOA@sets)=="GO:2001257"][[1]],]
and get 
                   symbol                 name
EBI-10814846 hcn4_human-1 HCN4 channel complex
EBI-10825931 hcn2_human-1 HCN2 channel complex

Assuming access to the GOA object is O(1) (can be wrong), I can maybe check annotations while iterating GO terms, so that would make it O(|GO|) for parsing .obo files and I can add associated gene names while building DAG?
I guess I use them for simplifying the code process of manually parsing. Would you please explain the disadvantage of using those packages? Runtime complexity?
For parsing obo files, I agree that parsing manually is more informative and controllable.

**Comment by hyginn** [comment]
Reviewed.
