### ISSUE TITLE
importPDB.R

### ISSUE THREAD

**Issue by bagherig** [hyginn/rete#108]
Hi Boris, 

Right now my unit tests check the sanity of the input only. I was wondering how I am supposed to check if my code works correctly, since it is supposed to take in an xyzMap containing a list of pdb.ids. Am I supposed to get actual data for this, with a gene and a list of pds.ids that align that gene and then calculate the expected output and see if my function returns that?

Thanks

**Comment by bagherig** [comment]
I also had another problem that I would appreciate your help with. I need to convert residue numbers in a sequence to residue numbers in a PDB file so I can extract the coordinate data for that residue. I was wondering, if the residue numbering starts from 25 (for example), this residue will actually be the first residue of the sequence right? And the only reason the residue numbering starts from 25 is that it is being compared to another PDB entry? Also if the numbering is missing some numbers, for example if it jumps from residue number 40 to 60, are residues 40 and 60 actually beside each other in the actual sequence? I remember you telling me yesterday that this could mean that there is some data missing from some PDB file, but in the case of 4OO9, it is numbered from 568 to 832, but between residues 678 and 680 are residues 1002 to 1162, which represents an inserted lyzozyme at this position (see [this](http://biology.stackexchange.com/questions/39122/do-residue-sequence-numbers-in-pdb-files-correspond-to-the-positions-in-the-back) for more info) so this makes me think that this jump in numbering doesn't actually mean that residues are missing.. But if a jump from 40 to 60 means that there are residues missing at these positions, then can I assume that there is 20 residues missing, or could there be more than 20 (because of insertion codes)?

If it could be more than 20 residues, then it seems impossible to convert sequence residue numbers to PDB residue numbers... 
From the Google searches I have done, this seems impossible.. 

Thanks

**Comment by hyginn** [comment]
I have thought about the procedure and you are right - there is a gap in the workflow at that point and we actually can't avoid another alignment: you would need to map to the sequence that was used for the BLAST search, residue numbers won't be sufficient. But you don't have the sequence, because the algorithm upstream only provides residue numbers. So there's nothing you can do.

- We need to revise the task. Please modify your function as follows:

(1) - Get the actual sequence from the coordinate records, in a vector of 
        amino-acid one letter codes.
(2) - Write a comment that from this point forward, that sequence would have
        to be mapped to the actual sequence that was used for a BLAST search.

Once that is done, submit your code, I will consider it to be complete; you don't have to actually compute the alignment.

B.

**Comment by bagherig** [comment]
> (1) - Get the actual sequence from the coordinate records, in a vector of amino-acid one letter codes.

Okay, my code already does this.

> (2) - Write a comment that from this point forward, that sequence would have to be mapped to the actual sequence that was used for a BLAST search.

I will do this, but my code from this point on also populates the GeneData object. Should I keep this code for marking purposes so you can see what I have done? and also maybe some of this code will be useful in the future. Or should I remove all of my code from this point on and just leave that comment?

Thanks,
Moeen

**Comment by hyginn** [comment]
Leave the code. I'd still like to see it.
Thanks,
Boris

**Comment by hyginn** [comment]
Reviewed
