### ISSUE TITLE
importM.COSMIC.R and test files implemented. Please review.

### ISSUE THREAD

**Issue by sharmah5** [hyginn/rete#25]
Hi Boris,

I've made some modifications to the import module. Please see my open pull request for the changes.

Here is the package check:

==> devtools::check(document = FALSE)

Setting env vars ---------------------------------------------------------------
CFLAGS  : -Wall -pedantic
CXXFLAGS: -Wall -pedantic
Building rete ------------------------------------------------------------------
"C:/PROGRA~1/R/R-33~1.2/bin/x64/R" --no-site-file --no-environ --no-save  \
  --no-restore --quiet CMD build  \
  "C:\Users\Hari\OneDrive\Documents\University\Year 4\Spring  \
  2017\BCB420H1\rete" --no-resave-data --no-manual 

* checking for file 'C:\Users\Hari\OneDrive\Documents\University\Year 4\Spring 2017\BCB420H1\rete/DESCRIPTION' ... OK
* preparing 'rete':
* checking DESCRIPTION meta-information ... OK
* excluding invalid files
Subdirectory 'R' contains invalid file names:
  'CosmicHGNC.tsv' 'cosmicCNV.rds' 'testCosmicCNA.tsv'
  'testCosmicCNAEmpty.tsv'
* checking for LF line-endings in source and make files
* checking for empty or unneeded directories
* building 'rete_0.1.0.tar.gz'

Setting env vars ---------------------------------------------------------------
_R_CHECK_CRAN_INCOMING_ : FALSE
_R_CHECK_FORCE_SUGGESTS_: FALSE
Checking rete ------------------------------------------------------------------
"C:/PROGRA~1/R/R-33~1.2/bin/x64/R" --no-site-file --no-environ --no-save  \
  --no-restore --quiet CMD check  \
  "C:\Users\Hari\AppData\Local\Temp\Rtmpghk15Q/rete_0.1.0.tar.gz" --as-cran  \
  --timings --no-manual 

* using log directory 'C:/Users/Hari/OneDrive/Documents/University/Year 4/Spring 2017/BCB420H1/rete.Rcheck'
* using R version 3.3.2 (2016-10-31)
* using platform: x86_64-w64-mingw32 (64-bit)
* using session charset: ISO8859-1
* using options '--no-manual --as-cran'
* checking for file 'rete/DESCRIPTION' ... OK
* checking extension type ... Package
* this is package 'rete' version '0.1.0'
* package encoding: UTF-8
* checking package namespace information ... OK
* checking package dependencies ... OK
* checking if this is a source package ... OK
* checking if there is a namespace ... OK
* checking for executable files ... OK
* checking for hidden files and directories ... OK
* checking for portable file names ... OK
* checking whether package 'rete' can be installed ... OK
* checking installed package size ... OK
* checking package directory ... OK
* checking DESCRIPTION meta-information ... OK
* checking top-level files ... OK
* checking for left-over files ... OK
* checking index information ... OK
* checking package subdirectories ... OK
* checking R files for non-ASCII characters ... OK
* checking R files for syntax errors ... OK
* checking whether the package can be loaded ... OK
* checking whether the package can be loaded with stated dependencies ... OK
* checking whether the package can be unloaded cleanly ... OK
* checking whether the namespace can be loaded with stated dependencies ... OK
* checking whether the namespace can be unloaded cleanly ... OK
* checking loading without being on the library search path ... OK
* checking dependencies in R code ... OK
* checking S3 generic/method consistency ... OK
* checking replacement functions ... OK
* checking foreign function calls ... OK
* checking R code for possible problems ... OK
* checking Rd files ... OK
* checking Rd metadata ... OK
* checking Rd line widths ... OK
* checking Rd cross-references ... OK
* checking for missing documentation entries ... OK
* checking for code/documentation mismatches ... OK
* checking Rd \usage sections ... OK
* checking Rd contents ... OK
* checking for unstated dependencies in examples ... OK
* checking examples ... OK
* checking for unstated dependencies in 'tests' ... OK
* checking tests ...
  Running 'testthat.R' OK
* DONE
Status: OK

R CMD check results
0 errors | 0 warnings | 0 notes

R CMD check succeeded

**Comment by hyginn** [comment]
Comments added.
