### ISSUE TITLE
preliminaryEdgeThreshTests.R (unit test design for edgeThresh)

### ISSUE THREAD

**Issue by FarzanT** [hyginn/rete#28]
Created a pull request regarding this addition.

**Comment by hyginn** [comment]
I just went over your pull request and found that my first two comments have not been addressed. So, raise another issue when all comments have been addressed, or reply to the comments (in the closed request) why you are not addressing them.

**Comment by hyginn** [comment]
I just went over your pull request and found that my first two comments have not been addressed. Please raise another issue when all comments have been addressed, or reply to the comments (in the closed request) why you are not addressing them.

**Comment by FarzanT** [comment]
"Please disregard edgeThresh", but you said that I should move on to designing unit tests, so I did not update edgeThresh (but I am working on it)
Would you review the unit test's design? As I mentioned in my email, I already have implemememted some of the simple parameter check tests, and need to be sure I'm on the right path. I'm currently working on understanding Tarjan's algorithm; once I do, I'll update edgeThresh

**Comment by FarzanT** [comment]
Also regarding disconnected components, I am confused as to whether simple components or strongly connected components are a matter of discussion here? If it's the former, I have a case where swapping two "bridges" results in two disconnected components.
