### ISSUE TITLE
Duplicate fname assignemnt in importNet.STRING.R

### ISSUE THREAD

**Issue by joelostblom** [hyginn/rete#3]
At https://github.com/hyginn/rete/blob/master/R/importNet.STRING.R#L116-#L117, `fname` is assigned twice:

```R
fCall[2] <- sprintf('fname = "%s", ', fName)
fCall[2] <- sprintf("fname = \"%s\", ", fName)
```
Not sure if the escapes and single/double quotes were originally meant for compatibility with different OSes somehow. Both give me the same output on Linux.

**Comment by hyginn** [comment]
Thanks - leftover from experiment with escaped vs. unescaped quotes. Fixed locally, will be in next push.
