### ISSUE TITLE
Unit test review for edgeThresh (found in testEdgeThresh.R)

### ISSUE THREAD

**Issue by FarzanT** [hyginn/rete#33]

**Comment by FarzanT** [comment]
Design is still in preliminaryTestEdgeThresh

**Comment by hyginn** [comment]
If I remember correctly, we had left off when I requested you to address comments on the workflow. So how are we now at the "review unit test" stage? I must have overlooked something.. enlighten me.

**Comment by FarzanT** [comment]
Please disregard EVERYTHING except for testEdgeThresh.R
GitHub is getting more confusing by the minute

**Comment by hyginn** [comment]
Comments added.
