### ISSUE TITLE
Merge request for COMBINE, question about global function

### ISSUE THREAD

**Issue by CharlesD1ng** [hyginn/rete#50]
Almost ready for merge.
Getting note that no visible global function definition for ‘hash’, after require(hash) in testthat.
Is there a proper way to attach hash to global dependency?

**Comment by hyginn** [comment]
You may add "hash" to the list of ```Imports``` in the ```DESCRIPTION``` file of the package. You should not need to ```require()``` it. But use ```hash::hash()``` or similar whenever you use one if its functions, to make it clear where non-standard functions come from.
