### ISSUE TITLE
importPSIMITAB problems

### ISSUE THREAD

**Issue by bronnil** [hyginn/rete#52]
1) How to make this program work for datasets where no header exists?
2)  The gene names are from uniprot but fastmap needs ENSP?

**Comment by hyginn** [comment]
Assume the header corresponds to MITAB format. Read one line and check your assumptions: write a little utility function ```isMITABformat()```, input the line you just read, ```strsplit()``` on tabs and ```grepl()``` the elements one by one, whether they match what you expect. ```stop()``` with error message if ```grepl()``` on an element returns ```FALSE```.

There is a fastmap version for uniprot, no?

**Comment by bronnil** [comment]
Will work on header and do more research of fast map

**Comment by bronnil** [comment]
One second, maybe I misunderstood. Do all mitab files only contain 16 columns? From the task page "Data Sources" it showed many columns- up to 14,473. Am I working with only 16 column mitab?
