### ISSUE TITLE
importPSIMITAB cant devtools::check()

### ISSUE THREAD

**Issue by bronnil** [hyginn/rete#56]
My code should be done but none of the shortcuts work for me. i.e. 

  Build and Reload Package:  'Cmd + Shift + B'
  Update Documentation:      'Cmd + Shift + D' or devtools::document()
  Test Package:              'Cmd + Shift + T'
  Check Package:             'Cmd + Shift + E'

**Comment by hyginn** [comment]
As I replied to you: post your problem to the list.
