### ISSUE TITLE
Tumour barcode normalization to upper case and dots

### ISSUE THREAD

**Issue by seneca-c** [hyginn/rete#58]
GitHub didn't want to let me make a second fork, so I'm working in a clean branch.  The only code that looked clean enough from my perspective to convert to dots (that needed conversion) was importM-COSMIC.  COMBINE will also need more extensive work to match the expected interface, as it expects SNV data to be RDS, not tab-delimited text.

Current state of the code:
https://github.com/hyginn/rete/compare/master...seneca-c:convertBarcode

**Comment by hyginn** [comment]
Not sure why you are raising in  Issue: is this FYI - or do you need me to do something?
