### ISSUE TITLE
importNet.PSIMITAB.R test 

### ISSUE THREAD

**Issue by bronnil** [hyginn/rete#62]
Ive uploaded the pseudo code for tests... its nearly identical to ImportString tests- almost all are valid and I cant see anything more to add?

https://github.com/bronnil/rete/blob/master/tests/testthat/testImportNet.MITAB.R

**Comment by hyginn** [comment]
Comments added and I have suggested a few more tests: there is more behaviour of this function that needs to be tested. Please continue - next is to write the tests, then build the code.
