### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by bronnil** [hyginn/rete#67]
Hi Boris,

I can't figure out how to test the scores of importNet.MITAB. It creates the scores in the middle of the function how do I get them out? If I should test when it is in a gG object that ut returns I dont know how to do that either.

Also "check that ID translation works"... not sure what this is referring to I didnt translate any IDs? do you mean when I clean the "uniprot:"? Again not sure how to test this if its done in the middle of the function?

**Comment by hyginn** [comment]
Test by observable behaviour, not internal states. Feed it an input with two high and one low score, and check that the resulting graph has two vertices - and variations on that.

ID translation? You'll need to get HGNC symbols for your gG object.

All clear?

B.

**Comment by bronnil** [comment]
I understand part 1 but I am feeding .df2gG what fastmap returns on my uniprot ids... not sure what I have to test there?

**Comment by hyginn** [comment]
Simply that you're getting known good HGNC symbols in your network if you're inputting known good UniProt IDs in the source file.
B.

**Comment by bronnil** [comment]
So... if I get enter 3 valid uniprot ids (that pass cutoff) and I get a gG with 3 vertices I am okay? The whole testing is vague to me but its starting to click in.

**Comment by hyginn** [comment]
And if your 3 vertices have the right HGNC symbols, the ID translation works too...

**Comment by bronnil** [comment]
I get it!
