### ISSUE TITLE
tests

### ISSUE THREAD

**Issue by bronnil** [hyginn/rete#73]
So... I changed string to mitab. made a smaller coresnippet.psimitab
found how to count vertices and how to get edge weight. 

Not sure how to find dropped?
No clue whatsoever about what Im checking wrt translations 

https://github.com/bronnil/rete/blob/master/tests/testthat/testImportNet(Version%202).MITAB.R

**Comment by hyginn** [comment]
Sounds like progress ...

Dropped: at some point in your code it will drop rows for which either one or the other UniProt ID can't be mapped to a gene symbol, right? (If not, it should). You need to report how many rows were dropped for that reason.

Re. ID translations - similar question: what percentage of IDs in the input failed to be mapped to gene symbols?

**Comment by bronnil** [comment]
Hi Boris,

I added two lines of code for these tests... am I doing it correctly

  expect_true(grepl("2 geneID can not be mapped to HGNC",      thisLog[7]))
  expect_true(grepl("20% of genes could not be mapped",        thisLog[8]))
