### ISSUE TITLE
SEL3D code draft ready for review

### ISSUE THREAD

**Issue by LindsayLiang** [hyginn/rete#75]
#74

**Comment by hyginn** [comment]
Task page:

> Before you begin, produce a manually determined result and define the structure of the MT (Match Table) object. Communicate this object structure to the implementer of the ImportPDB task so they can adjust their development accordingly.

Did you do that?

**Comment by hyginn** [comment]
Task page has **Requirements** section missing. What requirements are you developing against?

**Comment by LindsayLiang** [comment]
I haven’t had time to finish the page, but Moeen contacted me separately and I think he understood the final output I described to him.

-Lindsay

On Apr 1, 2017, at 3:02 PM, Boris Steipe <notifications@github.com<mailto:notifications@github.com>> wrote:


Task page:

Before you begin, produce a manually determined result and define the structure of the MT (Match Table) object. Communicate this object structure to the implementer of the ImportPDB task so they can adjust their development accordingly.

Did you do that?

**Comment by hyginn** [comment]
It's interesting that you would think of this as "finishing the page", rather than this being the very first step you do...

(That's just a comment btw.)

**Comment by LindsayLiang** [comment]
Could you clarify what ‘requirements’ you’re referring to?  I would’ve thought that a requirement would be the same as the preconditions above.  The only requirement I would need is cDNA of a length divisible by 3 and an internet connection?
On Apr 1, 2017, at 3:03 PM, Boris Steipe <notifications@github.com<mailto:notifications@github.com>> wrote:


Task page has Requirements section missing. What requirements are you developing against?

**Comment by hyginn** [comment]
The requirements of a piece of code specify its behaviour, including: what kind of data does it have to accept, what output will it produce, what resources will it consume. Also (but this is implied) including meta-requirements: needs to be integrated in R package, pass tests, scale. Also we might specify soft objectives including: easy to maintain, includes code validate correctness ...

**Comment by hyginn** [comment]
Your "final table" description includes 5 matches to the same range in the query. That would not be correct ...

**Comment by LindsayLiang** [comment]
Are you talking about something you ran the code on or something on the wiki page?  The page isn’t done yet, but if you ran the code, could you provide the example?


On Apr 1, 2017, at 3:50 PM, Boris Steipe <notifications@github.com<mailto:notifications@github.com>> wrote:


Your "final table" description includes 5 matches to the same range in the query. That would not be correct ...

**Comment by hyginn** [comment]
Hard to read. I think you are doing the right thing but in an awkward way. That's why I wanted to see pseudocode. I would have written a vector of logicals with which to keep track of matched residues, then use ```rle()``` to identify sections worth BLASTing again. ```intersect()``` against a vector of integers feels weird. Maybe it's the right way ... I don't know ... I didn't get a good sense of clearly understanding why you are doing this in the way you're doing them.

Anyway - comments added.

**Comment by hyginn** [comment]
> Are you talking about something you ran the code on or something on the wiki page? 

The description of your result on the Wiki page.

**Comment by LindsayLiang** [comment]
Updated/fixed.


On Apr 1, 2017, at 3:57 PM, Boris Steipe <notifications@github.com<mailto:notifications@github.com>> wrote:


Are you talking about something you ran the code on or something on the wiki page?

The description of your result on the Wiki page.
