### ISSUE TITLE
Pushed DIFFUSE.R and testDIFFUSE.R to whitleyo/rete repository

### ISSUE THREAD

**Issue by whitleyo** [hyginn/rete#78]
Output of check

==> devtools::check(document = FALSE)

Setting env vars ---------------------------------------------------------------
CFLAGS  : -Wall -pedantic
CXXFLAGS: -Wall -pedantic
Building rete ------------------------------------------------------------------
"C:/PROGRA~1/R/R-33~1.2/bin/x64/R" --no-site-file --no-environ --no-save  \
  --no-restore --quiet CMD build  \
  "C:\Users\HPDM1\Documents\CanadaUofT\4thYear\BCB420\rete" --no-resave-data  \
  --no-manual 

* checking for file 'C:\Users\HPDM1\Documents\CanadaUofT\4thYear\BCB420\rete/DESCRIPTION' ... OK
* preparing 'rete':
* checking DESCRIPTION meta-information ... OK
* checking for LF line-endings in source and make files
* checking for empty or unneeded directories
* building 'rete_0.1.0.tar.gz'

Setting env vars ---------------------------------------------------------------
_R_CHECK_CRAN_INCOMING_ : FALSE
_R_CHECK_FORCE_SUGGESTS_: FALSE
Checking rete ------------------------------------------------------------------
"C:/PROGRA~1/R/R-33~1.2/bin/x64/R" --no-site-file --no-environ --no-save  \
  --no-restore --quiet CMD check  \
  "C:\Users\HPDM1\AppData\Local\Temp\RtmpcP12Ns/rete_0.1.0.tar.gz" --as-cran  \
  --timings --no-manual 

* using log directory 'C:/Users/HPDM1/Documents/CanadaUofT/4thYear/BCB420/rete.Rcheck'
* using R version 3.3.2 (2016-10-31)
* using platform: x86_64-w64-mingw32 (64-bit)
* using session charset: ISO8859-1
* using options '--no-manual --as-cran'
* checking for file 'rete/DESCRIPTION' ... OK
* checking extension type ... Package
* this is package 'rete' version '0.1.0'
* package encoding: UTF-8
* checking package namespace information ... OK
* checking package dependencies ... OK
* checking if this is a source package ... OK
* checking if there is a namespace ... OK
* checking for executable files ... OK
* checking for hidden files and directories ... OK
* checking for portable file names ... OK
* checking whether package 'rete' can be installed ... OK
* checking installed package size ... OK
* checking package directory ... OK
* checking DESCRIPTION meta-information ... OK
* checking top-level files ... NOTE
Non-standard files/directories found at top level:
  'aggRef.Rdata' 'eggRef.Rdata' 'rete_2017-03-29.1.log'
  'rete_2017-03-30.1.log' 'rete_2017-03-30.2.log'
  'rete_2017-03-30.3.log'
* checking for left-over files ... OK
* checking index information ... OK
* checking package subdirectories ... OK
* checking R files for non-ASCII characters ... OK
* checking R files for syntax errors ... OK
* checking whether the package can be loaded ... OK
* checking whether the package can be loaded with stated dependencies ... OK
* checking whether the package can be unloaded cleanly ... OK
* checking whether the namespace can be loaded with stated dependencies ... OK
* checking whether the namespace can be unloaded cleanly ... OK
* checking loading without being on the library search path ... OK
* checking dependencies in R code ... OK
* checking S3 generic/method consistency ... OK
* checking replacement functions ... OK
* checking foreign function calls ... OK
* checking R code for possible problems ... OK
* checking Rd files ... OK
* checking Rd metadata ... OK
* checking Rd line widths ... OK
* checking Rd cross-references ... OK
* checking for missing documentation entries ... WARNING
Undocumented code objects:
  'importSNV.TCGA'
All user-level objects in a package should have documentation entries.
See chapter 'Writing R documentation files' in the 'Writing R
Extensions' manual.
* checking for code/documentation mismatches ... OK
* checking Rd \usage sections ... OK
* checking Rd contents ... OK
* checking for unstated dependencies in examples ... OK
* checking examples ... OK
* checking for unstated dependencies in 'tests' ... OK
* checking tests ...
  Running 'testthat.R'
Warning message:
running command '"C:/PROGRA~1/R/R-33~1.2/bin/x64/R" CMD BATCH --vanilla  "testthat.R" "testthat.Rout"' had status 1 
 ERROR
Running the tests in 'tests/testthat.R' failed.
Last 13 lines of output:
  grepl(sprintf("fgX = \"%s\"", testF), thisLog[3]) isn't true.
  
  
  Error in inherits(v, "igraph.vs") : could not find function "V"
  Calls: test_check ... eval -> eval -> <Anonymous> -> as.igraph.vs -> inherits
  testthat results ================================================================
  OK: 40 SKIPPED: 0 FAILED: 3
  1. Failure: a sane input gives an expected output (@testCombine.R#88) 
  2. Failure: a sane input gives an expected output (@testCombine.R#89) 
  3. Failure: a sane input gives an expected output (@testCombine.R#90) 
  
  Error: testthat unit tests failed
  Execution halted
* DONE
Status: 1 ERROR, 1 WARNING, 1 NOTE

See
  'C:/Users/HPDM1/Documents/CanadaUofT/4thYear/BCB420/rete.Rcheck/00check.log'
for details.

checking tests ... ERROR
Running the tests in 'tests/testthat.R' failed.
Last 13 lines of output:
  grepl(sprintf("fgX = \"%s\"", testF), thisLog[3]) isn't true.
  
  
  Error in inherits(v, "igraph.vs") : could not find function "V"
  Calls: test_check ... eval -> eval -> <Anonymous> -> as.igraph.vs -> inherits
  testthat results ================================================================
  OK: 40 SKIPPED: 0 FAILED: 3
  1. Failure: a sane input gives an expected output (@testCombine.R#88) 
  2. Failure: a sane input gives an expected output (@testCombine.R#89) 
  3. Failure: a sane input gives an expected output (@testCombine.R#90) 
  
  Error: testthat unit tests failed
  Execution halted

checking for missing documentation entries ... WARNING
Undocumented code objects:
  'importSNV.TCGA'
All user-level objects in a package should have documentation entries.
See chapter 'Writing R documentation files' in the 'Writing R
Extensions' manual.

checking top-level files ... NOTE
Non-standard files/directories found at top level:
  'aggRef.Rdata' 'eggRef.Rdata' 'rete_2017-03-29.1.log'
  'rete_2017-03-30.1.log' 'rete_2017-03-30.2.log'
  'rete_2017-03-30.3.log'
R CMD check results
1 error  | 1 warning  | 1 note 

R CMD check succeeded

**Comment by hyginn** [comment]
I don't see a pull request for this. Do you want to add one?

**Comment by whitleyo** [comment]
Pull request made

________________________________

**Comment by hyginn** [comment]
I don't see testDIFFUSE.R   please add.

**Comment by whitleyo** [comment]
That's weird, I see DIFFUSE.R in my R folder on github., and diffuseTest. My mistake, it was pull request number 80.


Owen


________________________________

**Comment by whitleyo** [comment]
Sorry,my bad, testDiffuse was not added until 9:04 in my latest push. But it's there now.


Owen

________________________________

**Comment by hyginn** [comment]
Comments added.

**Comment by whitleyo** [comment]
Can I have the changes done by Tuesday afternoon?


Owen

________________________________
