### ISSUE TITLE
Sel3D test case design ready for review

### ISSUE THREAD

**Issue by LindsayLiang** [hyginn/rete#83]

**Comment by RicardoRam** [comment]
You just closed your pull request. Do you still want it reviewed?

**Comment by LindsayLiang** [comment]
The one for the actual code?  You hadn't said anything in awhile so I assumed you were done so I thought to close it just to make changes.

**Comment by RicardoRam** [comment]
Oh okay. You left the issue open still so I wasn't sure if there was more to review.

**Comment by LindsayLiang** [comment]
Oh, sorry I didn't realize it would affect the test file too.  Were you done with reviewing the test file?

**Comment by RicardoRam** [comment]
Yeah I think you should write the actual test cases now. I think the ones you have look good.

**Comment by LindsayLiang** [comment]
Ok. Will do. Thanks.

**Comment by hyginn** [comment]
Open another Issue when done.
