### ISSUE TITLE
symmetrical edges

### ISSUE THREAD

**Issue by bronnil** [hyginn/rete#87]
Not sure how to check that symmetric edges are correctly added if requested also uploaded new code. in version 2

https://github.com/bronnil/rete/blob/master/tests/testthat/testImportNet(Version2).MITAB.R

**Comment by RicardoRam** [comment]
I added some comments to the pull request you made. The link above is to your repo so I can't add comments there.

**Comment by hyginn** [comment]
Re. symmetric edges - can't be implemented yet because we are waiting for a function that handles this. I had asked you to simply put a comment in the right place into your code. Nothing further required at this time.
