### ISSUE TITLE
ready for review - anuvar

### ISSUE THREAD

**Issue by Pruthv1** [hyginn/rete#97]
anuvar - task page ready for review (http://steipe.biochemistry.utoronto.ca/abc/students/index.php/BCB420_2017_Tasks/ANUVAR#Preconditions:_Packages)
anuvar.R - comments ready for review
testAnuvar.R - comments ready for review

**Comment by RicardoRam** [comment]
Function documentation, comments, and test pseudocode look good

**Comment by hyginn** [comment]
Comments added. Needs work.
